[profile.default]
src = 'contracts'
test = 'test'
libs = ['lib']
out = 'out'
cache_path = 'forge-cache'
verbosity = 2
solc_version = '0.8.17'
optimizer_runs = 200
via_ir = false
remappings = [
  "@utils=test/utils/",
  "@handlers=test/handlers/",
  "@mock=test/mock/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
[invariant]
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
