[profile.default]
src = 'contracts'
test = 'test'
libs = ['lib']
out = 'out'
cache_path  = 'forge-cache'
verbosity = 2
remappings = [
  "@utils=test/utils/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@mock=test/mock/"
]
