name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build
        run: forge build
      - name: Run tests
        run: forge test -vvv
  hardhat-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Setup
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build
        run: forge build
      - name: Get node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Setup
        run: yarn && sudo apt-get install lcov
      - name: Get coverage
        run: yarn coverage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn
      - run: yarn lint
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build
        run: forge build
      - name: Slither
        uses: crytic/slither-action@v0.3.0
        with:
          slither-version: "0.9.3"
